 env: "local" #local, dev, prod
 storage_path: "./storage.db"
 http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
 storage:
  host: "localhost"
  port: 5432
  database: "postgres"
  username: "postgres"
  password: "postgres"
  path:  "postgres://postgres:postgres@localhost:5432/postgres"
